const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '../frontend/.env' });

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('환경 변수가 설정되지 않았습니다.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function initDB() {
  console.log('Supabase 연결 중...', supabaseUrl);

  // 1. 테이블 생성 (RLS 정책 포함)
  // 참고: anon key로는 RLS 정책을 수정할 권한이 없을 수 있으므로, 
  // 기본적으로 테이블이 존재하는지 확인하고 없으면 생성하는 로직을 수행합니다.
  // 하지만 JS 클라이언트 자체로는 CREATE TABLE 쿼리를 직접 날리기 어렵습니다.
  
  // 대신, 더미 데이터를 삽입하여 테이블이 있는지 테스트하고, 
  // 없다면 마스터께 SQL 실행을 요청하는 메시지를 띄웁니다.
  
  const { error } = await supabase
    .from('reviews')
    .select('id')
    .limit(1);

  if (error) {
    console.error('테이블 확인 중 오류 발생:', error.message);
    if (error.message.includes('relation "reviews" does not exist')) {
      console.log('\n⚠️  "reviews" 테이블이 존재하지 않습니다.');
      console.log('아래 SQL을 Supabase SQL Editor에서 한 번만 실행해 주세요:\n');
      console.log(`
create table reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  novel_title text not null,
  platform_key text not null,
  novel_url text,
  content text not null,
  author_name text default '익명',
  rating int
);
alter table reviews enable row level security;
create policy "Enable insert for everyone" on reviews for insert with check (true);
create policy "Enable select for everyone" on reviews for select using (true);
      `);
    }
  } else {
    console.log('✅ "reviews" 테이블이 정상적으로 발견되었습니다!');
  }
}

initDB();
