-- ReviewNovel Reviews Table Schema for Supabase

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  novel_title text not null,
  platform_key text not null,
  novel_url text,
  content text not null,
  author_name text default '익명',
  rating int check (rating >= 1 and rating <= 5)
);

-- Enable Row Level Security
alter table reviews enable row level security;

-- Policies
create policy "Reviews are viewable by everyone" 
  on reviews for select 
  using (true);

create policy "Anyone can insert reviews" 
  on reviews for insert 
  with check (true);

-- Index for faster lookups by novel and platform
create index idx_reviews_novel_platform 
  on reviews(novel_title, platform_key);
